const BASE_FONT_SIZE = 16;
const BASE_HEIGHT = 300;
const BASE_WIDTH = 400;

export const FRAMES_PER_SECOND = {
  TWO: 2,
  TWENTY_FOUR: 24,
  SIXTY: 60,
};

export const FRAMES_PER_SECOND_INTERVAL = {
  TWO: 1000 / 2,
  TWENTY_FOUR: 1000 / 24,
  SIXTY: 1000 / 60,
};

export const COLOR = {
  BLACK: 'black',
  WHITE: 'white',
};

export const FONT = {
  NAME: 'dogicapixelbold',
  BASE_SIZE: BASE_FONT_SIZE,
  THREE_QUARTERS_BASE_SIZE: BASE_FONT_SIZE * 0.75,
  ONE_AND_A_HALF_BASE_SIZE: BASE_FONT_SIZE * 1.5,
  DOUBLE_BASE_SIZE: BASE_FONT_SIZE * 2,
};

export const SIZE = {
  BASE_HEIGHT,
  HALF_BASE_HEIGHT: 150,
  BASE_WIDTH,
  HALF_BASE_WIDTH: 200,
};
